# make_icons.py
#
# Current icons converted from icons.py into editable ASCII art.
# Edit the *_rows arrays, then run this script to regenerate icons.py.

WIDTH = 32
HEIGHT = 16

CHAR_TO_VALUE = {
    ".": 0,
    "1": 1,
    "2": 2,
    "3": 3,
    "4": 4,
    "5": 5,
    "6": 6,
    "7": 7,
    "8": 8,
    "9": 9,
    "a": 10,
    "b": 11,
    "c": 12,
    "d": 13,
    "#": 15,
}

def icon_from_ascii(rows):
    if len(rows) != HEIGHT:
        raise ValueError(f"Expected {HEIGHT} rows, got {len(rows)}")
    out = bytearray()
    for y, row in enumerate(rows):
        if len(row) != WIDTH:
            raise ValueError(f"Row {y} length {len(row)} != {WIDTH}")
        for ch in row:
            try:
                out.append(CHAR_TO_VALUE[ch])
            except KeyError:
                raise ValueError(f"Unknown character {ch!r} at row {y}")
    return out

def bytes_literal(data, wrap=16):
    parts = []
    for i in range(0, len(data), wrap):
        chunk = data[i:i+wrap]
        parts.append("    b'" + "".join(f"\\x{v:02x}" for v in chunk) + "'")
    return "(\n" + "\n".join(parts) + "\n)"

def write_icons_py(filename="icons.py"):
    icons = {
        "sky_sun": icon_from_ascii(sky_sun_rows),
        "sky_partly": icon_from_ascii(sky_partly_rows),
        "sky_cloud": icon_from_ascii(sky_cloud_rows),
        "precip_rain": icon_from_ascii(precip_rain_rows),
        "precip_snow": icon_from_ascii(precip_snow_rows),
        "precip_drizzle": icon_from_ascii(precip_drizzle_rows),
        "precip_thunder": icon_from_ascii(precip_thunder_rows),
        "precip_fog": icon_from_ascii(precip_fog_rows),
    }

    with open(filename, "w", encoding="utf-8") as f:
        f.write("# This file is generated by make_icons.py; do not edit directly.\n\n")
        for name, data in icons.items():
            f.write(f"{name} = {bytes_literal(data)}\n\n")

sky_sun_rows = [
    "...............d................",
    "........d......d......d.........",
    ".........d...........d..........",
    "..........b...a#a...b...........",
    "............7#####7.............",
    "............#######.............",
    "...........a#######a............",
    "......ddb..#########..bdd.......",
    "...........a#######a............",
    "............#######.............",
    "............7#####7.............",
    "..........b...a#a...b...........",
    ".........d...........d..........",
    "........d......d......d.........",
    "...............d................",
    "................................",
]

sky_partly_rows = [
    ".................d....aca....d..",
    "..................d..#####..d...",
    "....................#######.....",
    "....................#######a....",
    "...............7a7.#########.dd.",
    ".............aaaaaaa#######a....",
    "............aaaaaaaaa######.....",
    "...........7aaaaaaaaa#####......",
    "........79aaaaaaaaaaa69a9...d...",
    ".......aaaaaaaaaaaaaaaaaaa...d..",
    "......aaaaaaaaaaaaaaaaaaaaa.....",
    "......aaaaaaaaaaaaaaaaaaaaa9....",
    ".....aaaaaaaaaaaaaaaaaaaaaaa....",
    ".....aaaaaaaaaaaaaaaaaaaaaaa....",
    ".....aaaaaaaaaaaaaaaaaaaaaa9....",
    ".....79aaaaaaaaaaaaaaaaaa97.....",
]

sky_cloud_rows = [
    "................................",
    "..............48a84.............",
    ".............aaaaaaa............",
    "............aaaaaaaaa...........",
    "...........aaaaaaaaaaa..........",
    "...........aaaaaaaaaaa..........",
    "......48a8.aaaaaaaaaaa.8a84.....",
    ".....aaaaa9aaaaaaaaaaa9aaaaa....",
    "....aaaaaaaaaaaaaaaaaaaaaaaaa...",
    "....aaaaaaaaaaaaaaaaaaaaaaaaa4..",
    "...8aaaaaaaaaaaaaaaaaaaaaaaaa8..",
    "...aaaaaaaaaaaaaaaaaaaaaaaaaaa..",
    "...8aaaaaaaaaaaaaaaaaaaaaaaaa8..",
    "...7aaaaaaaaaaaaaaaaaaaaaaaaa7..",
    "...6aaaaaaaaaaaaaaaaaaaaaaaaa6..",
    "....79aaaaaaaaaaaaaaaaaaaaa97...",
]

precip_rain_rows = [
    "................................",
    "................................",
    ".....c......c......c......c.....",
    "....6c6....6c6....6c6....6c6....",
    "....ccc....ccc....ccc....ccc....",
    "....ccc....ccc....ccc....ccc....",
    "....7c7....7c7....7c7....7c7....",
    "....141....141....141....141....",
    "................................",
    ".........c......c......c........",
    "........6c6....6c6....6c6.......",
    "........ccc....ccc....ccc.......",
    "........ccc....ccc....ccc.......",
    "........7c7....7c7....7c7.......",
    "........141....141....141.......",
    "................................",
]

precip_snow_rows = [
    "................................",
    ".....a.............a............",
    "...9.#.9.........9.#.9..........",
    "....a#a...........a#a...........",
    "..a##b##a.......a##b##a.........",
    "....a#a...........a#a...........",
    "...9.#.9.........9.#.9..........",
    ".....a.............a............",
    "............a.............a.....",
    "..........9.#.9.........9.#.9...",
    "...........a#a...........a#a....",
    ".........a##b##a.......a##b##a..",
    "...........a#a...........a#a....",
    "..........9.#.9.........9.#.9...",
    "............a.............a.....",
    "................................",
]

precip_drizzle_rows = [
    "................................",
    "....a.......a.......a.......a...",
    "....6.......6.......6.......6...",
    "................................",
    "................................",
    "................................",
    "........a.......a.......a.......",
    "........6.......6.......6.......",
    "................................",
    "................................",
    "................................",
    "....a.......a.......a.......a...",
    "....6.......6.......6.......6...",
    "................................",
    "................................",
    "................................",
]

precip_thunder_rows = [
    ".............##d................",
    "..............##d....a....c.....",
    "....a..........##d...6...6c6....",
    "....6...........##c......ccc....",
    ".................##c.....ccc....",
    "..................##b....7c7....",
    "........a........##a.....141....",
    "........6.......##7.............",
    "...............##5.........a....",
    "...a..........##4..........8....",
    "...8......c....##...............",
    ".........6c6....#a......a.......",
    ".........ccc.....#8.....6....a..",
    ".........ccc......#7.........6..",
    ".........7c7.......#6...........",
    ".........141....................",
]

precip_fog_rows = [
    "................................",
    "................................",
    ".....bbbbb..bbbbbbbbb..bbb......",
    "................................",
    "................................",
    "...ccddddddddcc..ccddddddddddcc.",
    "................................",
    "................................",
    "..abbbbbaa...aabbbaaaaab...bbb..",
    "................................",
    "................................",
    "........ccccccbbbbcccccc........",
    "................................",
    "................................",
    "...aaaa..aaaaaaaaaaa..aaaaaaa...",
    "................................",
]

if __name__ == "__main__":
    write_icons_py("icons.py")
    print("Wrote icons.py")