import array
try:
    from config_local import *
except ImportError:
    from config import *
from common import *

# Integer phase counters (16-bit, 0..65535 = one full cycle).
# Steps derived from original float increments scaled to 16-bit integer space.
# AY: 0.03 rad/frame -> round(0.03 / 2pi x 65536) = 313
# WB: 0.03 x 0.31 rad/frame -> round(0.03 x 0.31 / 2pi x 65536) = 97
# TXT: 0.03 x 0.13 rad/frame -> round(0.03 x 0.13 / 2pi x 65536) = 41
_AY_STEP  = 313
_WB_STEP  = 129
_TXT_STEP = 55
_ay_phase  = 0
_wb_phase  = 0
_txt_phase = 0

# Torus parameters are stored in torus.bin (set in make_torus.py).
# _TORUS_N, _TORUS_M, _zoff, _zmax are set by _load_torus() at boot.
_TORUS_N = 0;  _TORUS_M = 0;  _zoff = 0;  _zmax = 0

# Torus data - all None until _load_torus() is called
_base_x = None;  _base_y = None;  _base_z = None  # unrotated vertices, int x256
_tp_x   = None;  _tp_y   = None;  _tp_z = None    # projected screen coords + camera Z (output)
_persp_lut  = None  # reciprocal LUT for perspective divide
_sin_lut    = None  # 256-entry sin table, int x256
_icx_lut    = None  # 256-entry cos(sin(phase) x WB_AMP) x 256 - wobble X rotation
_isx_lut    = None  # 256-entry sin(sin(phase) x WB_AMP) x 256
_base_nx    = None;  _base_ny = None;  _base_nz = None  # face normals, int x256
_torus_faces = None  # flat (a,b,c,d) quad index quads
_face_shades = None  # per-face shade output (0 = back-face culled)

# Fixed light direction in camera space - integer x256, no trig
_LIGHT_Y = 144
_LIGHT_Z = -192
_LIGHT_X  = 128

def _load_torus():
    """Load precomputed torus LUTs from torus.bin (generated by make_torus.py).
    All torus parameters are read from the bin header."""
    global _base_x, _base_y, _base_z, _tp_x, _tp_y, _tp_z
    global _persp_lut, _sin_lut, _icx_lut, _isx_lut
    global _base_nx, _base_ny, _base_nz, _torus_faces, _face_shades
    global _TORUS_N, _TORUS_M, _zoff, _zmax
    import struct
    with open('torus.bin', 'rb') as f:
        data = f.read()
    n, m, r_maj, r_min, _wb, _pd = struct.unpack_from("4B2H", data)
    _TORUS_N = n;  _TORUS_M = m
    _zoff = r_maj + r_min
    _zmax = 2 * (r_maj + r_min)
    NM = n * m
    persp_size = _zmax + 1
    off = 8
    _base_x     = array.array('i', data[off:off+NM*4]);          off += NM*4
    _base_y     = array.array('i', data[off:off+NM*4]);          off += NM*4
    _base_z     = array.array('i', data[off:off+NM*4]);          off += NM*4
    _persp_lut  = array.array('H', data[off:off+persp_size*2]);  off += persp_size*2
    _sin_lut    = array.array('h', data[off:off+256*2]);          off += 256*2
    _icx_lut    = array.array('h', data[off:off+256*2]);          off += 256*2
    _isx_lut    = array.array('h', data[off:off+256*2]);          off += 256*2
    _base_nx    = array.array('i', data[off:off+NM*4]);           off += NM*4
    _base_ny    = array.array('i', data[off:off+NM*4]);           off += NM*4
    _base_nz    = array.array('i', data[off:off+NM*4]);           off += NM*4
    _torus_faces = array.array('h', data[off:off+NM*4*2])
    _tp_x = array.array('h', [0] * NM)
    _tp_y = array.array('h', [0] * NM)
    _tp_z = array.array('h', [0] * NM)
    _face_shades = array.array('h', [0] * NM)

@micropython.viper
def _rotate_project(bx, by, bz, tpx, tpy, tpz, lut,
                    icy: int, isy: int, icx: int, isx: int, NM: int,
                    zoff: int, zmax: int):
    pbx  = ptr32(bx);   pby  = ptr32(by);   pbz  = ptr32(bz)
    ptpx = ptr16(tpx);  ptpy = ptr16(tpy);  ptpz = ptr16(tpz);  plut = ptr16(lut)
    for k in range(NM):
        lx = int(pbx[k]);  ly = int(pby[k]);  lz = int(pbz[k])
        x1 = ( lx * icy + lz * isy) >> 8
        z1 = (-lx * isy + lz * icy) >> 8
        y2 = ( ly * icx - z1 * isx) >> 8
        z2 = ( ly * isx + z1 * icx) >> 8
        ptpz[k] = z2                          # camera-space Z for depth sorting
        idx = (z2 >> 8) + zoff
        if idx < 0:       idx = 0
        elif idx > zmax:  idx = zmax
        recip = int(plut[idx])
        ptpx[k] = ((x1 * recip) >> 16) + 128
        ptpy[k] = ((y2 * recip) >> 16) + 100

@micropython.viper
def _shade_faces(bnx, bny, bnz, shades,
                 icy: int, isy: int, icx: int, isx: int,
                 lx: int, ly: int, lz: int, NM: int):
    pnx = ptr32(bnx);  pny = ptr32(bny);  pnz = ptr32(bnz)
    psh = ptr16(shades)
    for k in range(NM):
        nx = int(pnx[k]);  ny = int(pny[k]);  nz = int(pnz[k])
        nx1 = ( nx * icy + nz * isy) >> 8
        nz1 = (-nx * isy + nz * icy) >> 8
        ny2 = ( ny * icx - nz1 * isx) >> 8
        nz2 = ( ny * isx + nz1 * icx) >> 8
        dot = (nx1 * lx + ny2 * ly + nz2 * lz) >> 8
        if dot <= 0:
            psh[k] = 1                        # back face: draw dark (visible through hole)
        else:
            shade = (dot * 14 >> 8) + 1
            if shade > 15: shade = 15
            psh[k] = shade

def draw_demo(time_str, date_str):
    global _ay_phase, _wb_phase, _txt_phase

    N, M = _TORUS_N, _TORUS_M
    NM = N * M

    # Advance integer phases - no floats, no trig calls
    _ay_phase  = (_ay_phase  + _AY_STEP)  & 0xFFFF
    _wb_phase  = (_wb_phase  + _WB_STEP)  & 0xFFFF
    _txt_phase = (_txt_phase + _TXT_STEP) & 0xFFFF
    ay_idx  = _ay_phase  >> 8
    wb_idx  = _wb_phase  >> 8
    txt_idx = _txt_phase >> 8

    # Rotation matrix from LUTs - 4 array lookups, zero trig calls
    isy = _sin_lut[ay_idx]
    icy = _sin_lut[(ay_idx + 64) & 255]   # cos = sin(phase + quarter turn)
    icx = _icx_lut[wb_idx]
    isx = _isx_lut[wb_idx]

    # Light X follows torus spin; Y and Z stay fixed
    lx = _LIGHT_X

    _rotate_project(_base_x, _base_y, _base_z, _tp_x, _tp_y, _tp_z, _persp_lut,
                    icy, isy, icx, isx, NM, _zoff, _zmax)
    _shade_faces(_base_nx, _base_ny, _base_nz, _face_shades,
                 icy, isy, icx, isx, lx, _LIGHT_Y, _LIGHT_Z, NM)

    # Painter's algorithm: sort faces farthest-first by average camera-space Z
    tpz = _tp_z;  faces = _torus_faces
    order = []
    for k in range(NM):
        fi = k * 4
        a = faces[fi];  b = faces[fi+1];  c = faces[fi+2];  d = faces[fi+3]
        order.append((tpz[a] + tpz[b] + tpz[c] + tpz[d], k))
    order.sort(reverse=True)

    gfx.cls(BLACK)
    tpx = _tp_x;  tpy = _tp_y;  shades = _face_shades
    for _, k in order:
        fi = k * 4
        a = faces[fi];  b = faces[fi+1];  c = faces[fi+2];  d = faces[fi+3]
        gfx.polygon(tpx[a], tpy[a], tpx[b], tpy[b],
                    tpx[c], tpy[c], tpx[d], tpy[d], shades[k], True)

    # Time + date overlay drifts horizontally together - integer LUT, no trig
    # Amplitude 72 keeps a 10-char date string within screen bounds
    text_x = (_sin_lut[txt_idx] * 72 >> 8) + 96
    gfx.print_string(text_x, 176, time_str, BLACK, WHITE)
    gfx.print_string(text_x, 184, date_str, BLACK, WHITE)

def run(pin=None):
    gfx.init()
    gfx.set_border(0)
    gfx.cls(BLACK)

    wlan = connect_wifi()
    if wlan is not None:
        sync_ntp(clear=True)

    _load_torus()

    last_day = None
    pincounter = 0

    while True:
        active, pincounter = check_pin_stable(pin, 0, pincounter)
        if not active:
            break

        now = time.time()
        t   = time.localtime(now + _utc_offset(now))
        yr, mon, day, h, m, s = t[0], t[1], t[2], t[3], t[4], t[5]

        if day != last_day:
            last_day = day
            reconnect_wifi(wlan)
            try:
                ntptime.settime()
            except Exception:
                pass

        if CLOCK_12H:
            h12 = h % 12 or 12
            time_str = "{}:{:02d}:{:02d}{}".format(h12, m, s, "am" if h < 12 else "pm")
        else:
            time_str = "{:02d}:{:02d}:{:02d}".format(h, m, s)
        sep = DATE_SEP
        if DATE_ORDER == 'MDY':   date_str = '{}{}{}{}{}'.format(mon, sep, day, sep, yr)
        elif DATE_ORDER == 'YMD': date_str = '{}{}{}{}{}'.format(yr,  sep, mon, sep, day)
        else:                     date_str = '{}{}{}{}{}'.format(day, sep, mon, sep, yr)

        draw_demo(time_str, date_str)
        time.sleep_ms(10)
